intexdental/backend/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('review/', views.reviewpage, name='review'),
    path('gallery/', views.gallerypage, name='gallery'),
    path('questions/', views.questionspage, name='questions'),
    path('contacts/', views.contactspage, name='contacts'),
    path('price/', views.pricepage, name='price'),
    path('service/<slug:slug>/', views.servicepage, name='service'),
    path('doctors/', views.doctorspage, name='doctors'),
    path('doctor/<slug:slug>/', views.doctorpage, name='doctor'),
    path('stocks/', views.stockspage, name='stocks'),
    path('articles/', views.articlespage, name='articles'),
    path('article/<slug:slug>', views.articlepage, name='article'),
    path('shares/', views.shares, name='shares'),
    path('services/', views.services, name='services'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('category/<slug:slug>/', views.category, name='category'),
]

form_urls = [
    path('call-back-form/', views.form, name='form'),
    path('callback_full/', views.callback_full, name='callback_full'),
    path('thanks/', views.thanks, name='thanks'),
]

urlpatterns += form_urls

intexdental/intexdental/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('backend.main.urls', namespace='main')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # re_path(r'^', include('django_telegrambot.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    print('rosseta!')
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

intexdental/intexdental/templates/includes/breadcrumbs.html
<section class="breadcrumbs">
    <div class="container">
        {% for crumbs in bredcrumbs %}
            <a class="main-page {% if forloop.last %} level-page {% endif %}"
                    {% if crumbs.1 %}
               href="{% url crumbs.1 %}"
                    {% endif %}
            > {{ crumbs.0 }} </a>
            {% if not forloop.last %}
                <span class="main-page">-</span>
            {% endif %}
        {% endfor %}
    </div>
</section>

intexdental/intexdental/templates/includes/call_back_form.html
{% load poll_extras %}
{% load i18n %}
{% get_callback_form as form %}

<form action="{% url 'main:form' %}"
      method="post"
      class="form" id="call_back_form">
    {% csrf_token %}
    {% for field in form.form %}
        {% if field.html_name == 'name_user' %}
            {{ field }}
            <span class="js-error-field error-field hide" data-name="{{ field.html_name }}">
                {% trans 'Длинна строки не должна превышать 255 символов' %}
            </span>
        {% else %}
            {{ field }}
        {% endif %}
    {% endfor %}
    <button class="submit-btn" type="submit">{% trans 'Отправить заявку' %}</button>
</form>

<div class="js-thx thanks-text hide">
    {% trans 'Спасибо что написали нам' %}
</div>

intexdental/intexdental/templates/includes/call_form_full.html
{% load i18n %}
{% load poll_extras %}
{#service-form default section_class#}
{#service-block-form-wrap default wrap #}
{#service-block-form default form #}
<section id="form" class="{% if section_class %}
{{ section_class }}
{% else %}
service-form
{% endif %}">
    <div class="container">
        <div class="{% if wrap %}
{{ wrap }}
{% else %}
service-block-form-wrap
{% endif %}
">
            <div class="{% if form %}
{{ form }}
{% else %}
service-block-form
{% endif %}
">
                <div class="form_main_screen_wrap">
                    <p class="form-title">{% trans 'ЗАПИСАТЬСЯ НА ПРИЕМ' %}</p>
                    <p class="js-form-help thanks-text hide">
                        {% trans ' Спасибо за оставленную заявку! Мы Вам обязательно перезвоним' %}
                    </p>
                    {% get_services as services %}
                    {% get_doctors as doctors %}
                    <form class="form" action="{% url 'main:callback_full' %}" method='post' id="full_form">
                        {% csrf_token %}
                        <div class="form-wrap">
                            <div class="form-left">
                                <input type="text" placeholder="*Имя" name="name">
                                <input type="text" placeholder="*Номер телефона" id="phone" name="phone">
                                <select name="service_id" id="usluga">
                                    <option value="-1">Определенная услуга</option>
                                    {% for service in services %}
                                        <option value="{{ service.0 }}">{{ service.1 }}</option>
                                    {% endfor %}
                                </select>
                                <select name="doctor_id" id="doctor">
                                    <option value="-1">Выберите врача</option>
                                    {% for doctor in doctors %}
                                        <option value="{{ doctor.id }}"
                                        >{{ doctor.fio }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-right">
                                <textarea rows="10" name="text" placeholder="Текст сообщения"></textarea>
                            </div>
                        </div>
                        <button class="submit-btn" type="submit">Отправить заявку</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

intexdental/intexdental/templates/includes/footer.html
{% load i18n %}
{% load solo_tags %}
{% load poll_extras %}
{% load static %}

{% block content %}
<div class="footer-wrapper">
    <footer>
        <div id="google_map" class="google_map">
        </div>
        <div class="container">
            <div class="contact-footer">
                <p class="contact-title">{% trans 'Контакты' %}</p>
                <a class="contact-tel" href="tel:(067) 465 00 13">(067) 465 00 13</a>
                <p class="address">{% trans 'Киев, ул. Черняховского 18' %}</p>
                <a class="address" href="mailto:intexdentalnuvky@gmail.com">{% trans 'intexdentalnuvky@gmail.com' %}</a>
            </div>
        </div>
    </footer>
    <div class="bottom-bar">
        <div class="container">
            <div class="footer-wrap">
                <div class="logo-footer">
                    <img class="img-foot" src="{% static 'images/INTEXDENTAL_white.svg' %}" alt="">
                </div>
                <div class="menu-footer">
                    <nav>
                          <a href="{% url 'main:stocks' %}" {% if page == 'stocks' %} class="active" {% endif %}>{% trans 'Акции' %}</a>
                    <a {% if page == 'price' %} class="active" {% endif %} href="{% url 'main:price' %}">{% trans 'Услуги' %}</a>
                    <a  {% if page == 'doctors' %} class="active" {% endif %} href="{% url 'main:doctors' %}">{% trans 'Наша команда' %}</a>
                    <a {% if page == 'review' %} class="active" {% endif %} href="{% url 'main:review' %}">{% trans 'Отзывы' %}</a>
                    <a {% if page == 'gallery' %} class="active" {% endif %} href="{% url 'main:gallery' %}">{% trans 'Галерея' %}</a>
                    <a {% if page == 'articles' %} class="active" {% endif %} href="{% url 'main:articles' %}">{% trans 'Статьи' %}</a>
                    <a {% if page == 'contacts' %} class="active" {% endif %} href="{% url 'main:contacts' %}">{% trans 'Контакты' %}</a>
                    </nav>
                </div>
            </div>
            <p class="bottom-text">{% trans 'Intex Clinic. Все права защищены' %}</p>
        </div>
</div>
    </div>
{% endblock %}

{% block js %}


{% endblock %}

intexdental/intexdental/templates/includes/header.html
{% load i18n %}
{% load poll_extras %}
{% load static %}
{% get_language request as language %}
<header class="header-white">
    <div class="container">
        <div class="header-wrap">
            <div class="logo-header">
                <a href="/">
                    <img class="img-logoW display-none" src="{% static 'images/INTEXDENTAL_white.svg' %}" alt="">
                    <img class="img-logoG " src="{% static 'images/INTEXDENTAL_green.png' %}" alt="">
                </a>
            </div>
            <div class="menu-header">
                <nav>
                    <a href="{% url 'main:stocks' %}" {% if page == 'stocks' %} class="active" {% endif %}>{% trans 'Акции' %}</a>
                    <a {% if page == 'price' %} class="active" {% endif %} href="{% url 'main:price' %}">{% trans 'Услуги' %}</a>
                    <a  {% if page == 'doctors' %} class="active" {% endif %} href="{% url 'main:doctors' %}">{% trans 'Наша команда' %}</a>
                    <a {% if page == 'review' %} class="active" {% endif %} href="{% url 'main:review' %}">{% trans 'Отзывы' %}</a>
                    <a {% if page == 'gallery' %} class="active" {% endif %} href="{% url 'main:gallery' %}">{% trans 'Галерея' %}</a>
                    <a {% if page == 'articles' %} class="active" {% endif %} href="{% url 'main:articles' %}">{% trans 'Статьи' %}</a>
                    <a {% if page == 'contacts' %} class="active" {% endif %} href="{% url 'main:contacts' %}">{% trans 'Контакты' %}</a>
                </nav>
            </div>
            <div class="mob-menu">
                <div class="icon-menu">
                    <hr>
                    <hr>
                    <hr>
                    <span>X</span>
                </div>
                <div class="menu-mob-wrap">
                    <div class="menu-header-mob">
                        <nav>
                            <a href="{% url 'main:stocks' %}" class="active">{% trans 'Акции' %}</a>
                            <a href="{% url 'main:price' %}">{% trans 'Услуги' %}</a>
                            <a href="{% url 'main:doctors' %}">{% trans 'Наша команда' %}</a>
                            <a href="{% url 'main:review' %}">{% trans 'Отзывы' %}</a>
                            <a href="{% url 'main:gallery' %}">{% trans 'Галерея' %}</a>
                            <a href="{% url 'main:articles' %}">{% trans 'Статьи' %}</a>
                            <a href="{% url 'main:contacts' %}">{% trans 'Контакты' %}</a>
                        </nav>
                    </div>
                </div>
            </div>
            <div class="language-wrap">
                {% for lang in language.LANGUAGES %}
                    {% if lang.0 == language.SELECTEDLANG %}
                        <div class="">
                            <button class="{% if lang.0 == request.LANGUAGE_CODE %} active-lang {% endif %}">
                                {{ lang.0 }}
                            </button>
                        </div>
                    {% else %}
                        <div>
                            <form class="js-set-lang {% if lang.0 == request.LANGUAGE_CODE %}order-1{% endif %}"
                                  action="{% url 'set_language' %}" method="post"> {% csrf_token %}
                                <input name="next" type="hidden" value="{{ language.redirect_to }}"/>
                                <input type="hidden" name="language" value="{{ lang.0 }}">
                                <button class="leng {% if lang.0 == request.LANGUAGE_CODE %} active-lang {% endif %}">{{ lang.0 }}
                                </button>
                            </form>
                        </div>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="contact-header">
                <a href="tel:(067) 465 00 13"> (067) 465 00 13</a>
                <p>{% trans 'Киев, ул. Черняховского 18' %}</p>
            </div>

        </div>
    </div>

</header>