intexdental/backend/main/urls.py
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.homepage, name='home'),
    path('review/', views.reviewpage, name='review'),
    path('gallery/', views.gallerypage, name='gallery'),
    path('questions/', views.questionspage, name='questions'),
    path('contacts/', views.contactspage, name='contacts'),
    path('price/', views.pricepage, name='price'),
    path('service/<slug:slug>/', views.servicepage, name='service'),
    path('doctors/', views.doctorspage, name='doctors'),
    path('doctor/<slug:slug>/', views.doctorpage, name='doctor'),
    path('stocks/', views.stockspage, name='stocks'),
    path('articles/', views.articlespage, name='articles'),
    path('article/<slug:slug>', views.articlepage, name='article'),
    path('shares/', views.shares, name='shares'),
    path('services/', views.services, name='services'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('category/<slug:slug>/', views.category, name='category'),
]

form_urls = [
    path('call-back-form/', views.form, name='form'),
    path('callback_full/', views.callback_full, name='callback_full'),
    path('thanks/', views.thanks, name='thanks'),
]

urlpatterns += form_urls

intexdental/intexdental/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    re_path(r'^i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),
    path('', include('backend.main.urls', namespace='main')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # re_path(r'^', include('django_telegrambot.urls')),
)

if 'rosetta' in settings.INSTALLED_APPS:
    print('rosseta!')
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_ROOT, document_root=settings.STATIC_URL)

intexdental/backend/main/forms.py
from django import forms
# from django.utils.translation import ugettext as _
from django.utils.translation import ugettext_lazy as _, ugettext_noop as _noop
from .models import CallBackForm


class CallBackFormFront(forms.ModelForm):
    class Meta:
        model = CallBackForm
        # fields = '__all__'
        exclude = ['date', 'status', 'doctor', 'service' , 'service_1']

    def __init__(self, *args, **kwargs):
        super(CallBackFormFront, self).__init__(*args, **kwargs)
        for key, field in self.fields.items():
            if isinstance(field.widget, forms.TextInput) or \
                    isinstance(field.widget, forms.Textarea) or \
                    isinstance(field.widget, forms.DateInput) or \
                    isinstance(field.widget, forms.DateTimeInput) or \
                    isinstance(field.widget, forms.TimeInput):
                field.widget.attrs.update({'placeholder': field.label})

intexdental/backend/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .forms import CallBackFormFront
from htmlmin.decorators import minified_response
from .models import Sale, Category, Doctor, CallBackForm, Article, StaticInfo, Review
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import ugettext_lazy as _, ugettext_noop as _noop
# Create your views here.

import requests

BOT_TOKEN = '1150204605:AAH6eqYQM5lBhFPjWp1WoaLHoubWOIxfUn0'
BOT_CHAT_ID = '-467576581'


def get_sales():
    return Sale.objects.filter(status=1)


@minified_response
def homepage(request):
    ctx = {
        'page': 'home'
    }
    ctx['sales'] = get_sales()

    return render(request, 'main/home.html', ctx)


@minified_response
def reviewpage(request):
    ctx = {
        'page': 'review'
    }
    bread = [(_('Головна'), 'main:home'), (_('Отзывы'), '')]
    ctx['bredcrumbs'] = bread
    if request.method == 'POST':
        name = request.POST.get('name')
        text = request.POST.get('text')
        msg_to_telegramm = 'Отзыв \nІм’я: {}\n text: {}'.format(name, text)
        send_text = 'https://api.telegram.org/bot' \
                    + BOT_TOKEN + '/sendMessage?chat_id=' \
                    + BOT_CHAT_ID + '&parse_mode=Markdown&text=' + msg_to_telegramm
        requests.get(send_text)
        Review.objects.create(
            name=name,
            text=text,
        )
        return JsonResponse({
            'status': True
        })
    return render(request, 'main/review.html', ctx)


@minified_response
def gallerypage(request):
    ctx = {
        'page': 'gallery'
    }
    bread = [(_('Головна'), 'main:home'), (_('Галерея'), '')]
    ctx['bredcrumbs'] = bread
    return render(request, 'main/gallery.html', ctx)


@minified_response
def questionspage(request):
    ctx = {
        'page': 'questions'
    }
    bread = [(_('Головна'), 'main:home'), (_('Частые вопросы'), '')]
    ctx['bredcrumbs'] = bread
    return render(request, 'main/questions.html', ctx)


@minified_response
def contactspage(request):
    ctx = {
        'page': 'contacts'
    }

    return render(request, 'main/contacts.html', ctx)


@minified_response
def pricepage(request):
    ctx = {}
    ctx.update({
        'page': 'price'
    })
    categories = Category.objects.filter(status=True)
    ctx['categories'] = categories
    bread = [(_('Головна'), 'main:home'), (_('Услуги'), '')]
    ctx['bredcrumbs'] = bread
    return render(request, 'main/price.html', ctx)


@minified_response
def servicepage(request, slug):
    ctx = {}
    ctx['page'] = 'service'
    bread = [('Головна', 'main:home')]

    try:
        service = StaticInfo.objects.get(slug=slug)
        ctx['service'] = service
        bread.append((service.name, ''))
    except Exception as e:
        print(type(e), e)
    ctx['bredcrumbs'] = bread
    return render(request, 'main/service.html', ctx)


@minified_response
def doctorspage(request):
    ctx = {
        'page': 'doctors'
    }
    bread = [('Головна', 'main:home'), ('Наша команда', '')]
    ctx['bredcrumbs'] = bread
    return render(request, 'main/doctors.html', ctx)


@minified_response
def doctorpage(request, slug):
    ctx = {
        'page': 'doctor'
    }
    try:
        doctor = Doctor.objects.get(slug=slug)
        ctx['doctor'] = doctor
        bread = [
            ('Головна', 'main:home'),
            ('Наша команда', 'main:doctors'),
            (doctor.fio, ''),
        ]
        ctx['bredcrumbs'] = bread
    except Exception as e:
        print(type(e), e)
    return render(request, 'main/doctor.html', ctx)


@minified_response
def articlespage(request):
    ctx = {
        'page': 'articles'
    }
    all_articles = Article.objects.filter(status=True).order_by('-id')

    page = request.GET.get('page', 1)

    paginator = Paginator(all_articles, 6)
    try:
        all_articles = paginator.page(page)
    except PageNotAnInteger:
        all_articles = paginator.page(1)
    except EmptyPage:
        all_articles = paginator.page(paginator.num_pages)

    ctx['all_articles'] = all_articles
    bread = [('Головна', 'main:home'), ('Статьи', '')]
    ctx['bredcrumbs'] = bread
    return render(request, 'main/articles.html', ctx)


@minified_response
def articlepage(request, slug):
    ctx = {
        'page': 'article'
    }
    try:
        article = Article.objects.get(slug=slug)
        ctx['article'] = article
        bread = [('Головна', 'main:home'), ('Статьи', 'main:articles')]
        bread.append((article.title, ''))
        ctx['bredcrumbs'] = bread
    except Exception as e:
        print(type(e), e)

    return render(request, 'main/article.html', ctx)


@minified_response
def stockspage(request):
    bread = [('Головна', 'main:home')]
    bread.append(('Акции', ''))
    ctx = {
        'page': 'stocks',
        'bredcrumbs': bread
    }

    return render(request, 'main/stocks.html', ctx)


@minified_response
def form(request):
    ctx = {}
    # if request.method == 'POST':
    form = CallBackFormFront(request.POST)
    if form.is_valid():
        form.save()
        print('asdasdas')
        name = form.cleaned_data['name_user']
        phone_number = form.cleaned_data['phone_number']
        msg = form.cleaned_data['msg']
        msg_to_telegramm = 'Заявка \nІм’я: {}\n Номер телефона: {} \n Сообщение: {}'.format(name, phone_number, msg)
        send_text = 'https://api.telegram.org/bot' + BOT_TOKEN + '/sendMessage?chat_id=' + BOT_CHAT_ID + '&parse_mode=Markdown&text=' + msg_to_telegramm
        requests.get(send_text)
        return redirect('main:thanks')
    else:
        return JsonResponse({
            'status': False
        })


def thanks(request):
    return render(request, 'thanks.html', {
        "page": 'thanks'
    })


@minified_response
def callback_full(request):
    name = request.POST.get('name')
    phone = request.POST.get('phone')
    text = request.POST.get('text')
    service_id = request.POST.get('service_id')
    doctor_id = None
    try:
        # service_id = int(request.POST.get('service_id'))
        doctor_id = int(request.POST.get('doctor_id'))
    except Exception as e:
        print(type(e), e)
    form = CallBackForm()
    form.name_user = name
    form.phone_number = phone
    form.msg = text
    form.service_1 = service_id
    # form.service_id = service_id if service_id != -1 else None
    form.doctor_id = doctor_id if doctor_id != -1 else None
    form.save()
    msg_to_telegramm = 'Заявка \nІм’я: {}\nНомер телефона: {} \nУслуга : {} \nСообщение: {}'.format(name, phone,
                                                                                                    [value for
                                                                                                     key, value in
                                                                                                     CallBackForm.SERVICE_CHOICE_1
                                                                                                     if
                                                                                                     key == service_id][
                                                                                                        0], text)
    send_text = 'https://api.telegram.org/bot' + BOT_TOKEN + '/sendMessage?chat_id=' + BOT_CHAT_ID + '&parse_mode=Markdown&text=' + msg_to_telegramm
    requests.get(send_text)
    return redirect('main:thanks')


@minified_response
def shares(request):
    ctx = {}
    ctx['sales'] = get_sales()
    test = [('Головна', 'main:home'), ('Акции', '')]
    ctx['bredcrumbs'] = test
    return render(request, 'main/shares.html', ctx)


@minified_response
def detail(reques, pk):
    test = [('Головна', 'main:home'), ('Акции', 'main:shares')]
    sale = Sale.objects.get(pk=pk).title
    test.append((sale, ''))
    return render(reques, 'main/test.html', {
        'bredcrumbs': test
    })


@minified_response
def category(request, slug):
    ctx = {}
    test = [('Головна', 'main:home'), ('Цены', 'main:services')]
    category = Category.objects.get(slug=slug)
    test.append((category.name, ''))
    ctx['category'] = category
    ctx['bredcrumbs'] = test
    return render(request, 'main/category.html', ctx)


@minified_response
def services(request):
    ctx = {}
    test = [('Головна', 'main:home'), ('Цены', '')]
    ctx['bredcrumbs'] = test
    return render(request, 'main/services.html', ctx)

intexdental/intexdental/templates/main/article.html
{% extends "index.html" %}
{% load i18n %}
{% load solo_tags %}
{% load poll_extras %}
{% load static %}
{% block title %}
    {{ article.title }}
{% endblock %}

{% block meta %}
    <meta name="author" content="Avalan.studio"/>
    <meta name="position" content="50.448091, 30.521688"/>
    <meta name="description"
          content="{{ article.meta_desc }}"/>

    <meta name="keywords"
          content="{{ article.meta_keywords }}"/>
    <meta name="copyright" content="{% trans 'Всі права належать' %} Avalan.studio"/>
{% endblock %}




{% block content %}
    <section class="doctors-over">
        {% include "includes/breadcrumbs.html" %}
        <section class="service-content">
            <div class="container">
                <div class="service-title">
                    <h1>{{ article.title }}</h1>
                    <a class="btn-contact js-anchor" data-to="form">{% trans 'ЗАПИСАТЬСЯ НА ПРИЕМ' %}</a>
                </div>

            </div>

        </section>
        <section class="doctors-wrap articles-wrap">
            <div class="container">
                <div class="article-one-wrap">
                    <div class="text-article">
                        <div class="edition">
                            <p class="article-date">{{ article.date }}</p>
                            <div class="share-wrap">
                                <p class="share-article">{{ article.author.fio }}</p>

                            </div>
                        </div>

                        <p class="article-annotation">{{ article.lead }}</p>

                        {#                        <img src="{% static 'images/article-img.png' %}" alt="" class="article-img">#}
                        <div class="article-content">
                            {{ article.content|safe }}
                        </div>
                    </div>
                    <div class="doctors-general art-add">
                        <p class="articles-similar">Похожие статьи</p>
                        {% for art in article.articles.all %}
                        <div class="doctor-one article-one" style="position: relative">
                                <a href="{% url 'main:article' slug=art.slug %}" class="abs-link"></a>
                            <div class="img-doctor-wrap">
                                {% if art.photo %}
                                    <img src="{{ art.photo.url }}" alt="" class="doctor-img">
                                {% else %}
                                <img src="{% static 'images/doctor.png' %}" alt="" class="doctor-img">
                                {% endif %}
                                <div class="hover-article">
                                </div>
                            </div>
                            <p class="doctor-name">{{art.title}}</p>
                            <p class="doctor-prof">{{art.lead}}</p>
                            <p class="article-date">{{art.date}}</p>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </section>

    </section>
    {% include 'includes/call_form_full.html' with section_class='price-form' wrap='price-block-form-wrap' form='price-block-form' %}
{% endblock %}

{% block js %}
    <script>
        App.home.init();
        App.category.init();
        // App.form.init();
    </script>
{% endblock %}
{% block extra_js %}
    <script>
        App.phone_mask('phone');
        App.scrool_to_block();
    </script>
{% endblock %}

intexdental/intexdental/templates/main/articles.html
{% extends "index.html" %}
{% load i18n %}
{% load solo_tags %}
{% load poll_extras %}
{% load static %}

{% block title %} {% trans 'Статьи' %} {% endblock %}

{% block meta %}
    {% get_solo 'meta.MetaBlog' as block_meta %}
    <meta name="author" content="Avalan.studio"/>
    <meta name="position" content="50.448091, 30.521688"/>
    <meta name="description"
          content="{{ block_meta.meta_desc }}"/>

    <meta name="keywords"
          content="{{ block_meta.meta_keywords }}"/>
    <meta name="copyright" content="{% trans 'Всі права належать' %} Avalan.studio"/>
{% endblock %}


{% block content %}
    <section class="doctors-over">
        {% include "includes/breadcrumbs.html" %}
        <section class="service-content">
            <div class="container">
                <div class="service-title">
                    <h1>{% trans 'Статьи' %}</h1>
                    <a class="btn-contact js-anchor" data-to="form">{% trans 'ЗАПИСАТЬСЯ НА ПРИЕМ' %}</a>
                </div>

            </div>

        </section>
        <section class="doctors-wrap articles-wrap">
            <div class="container">
                <div class="doctors-general">
                    {% for article in all_articles %}
                        <div class="doctor-one article-one" style="position:relative;">
                            <a href="{% url 'main:article' slug=article.slug %}" class="abs-link"></a>
                            <div class="img-doctor-wrap">
                                {% if article.photo %}
                                    <img src="{{ article.photo.url }}" alt="" class="doctor-img">
                                {% else %}
                                    <img src="{% static 'images/doctor.png' %}" alt="" class="doctor-img">
                                {% endif %}
                                <div class="hover-article">
                                </div>
                            </div>
                            <p class="doctor-name">{{ article.title }}</p>
                            <p class="doctor-prof">{{ article.lead }}</p>
                            <p class="article-date">{{ article.date }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
        <section class="pagination">
            <div class="pagination-wrap">
                {% if all_articles.has_other_pages %}
                    {% if all_articles.has_previous %}
                        <a href="?page={{ all_articles.previous_page_number }}">
                                <span class="arr-prew">
                 <svg width="12" height="18" viewBox="0 0 12 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0.999388 9.70236L9.00962
17.7124C9.19488 17.8979 9.4422 18 9.7059 18C9.96961 18 10.2169
17.8979 10.4022 17.7124L10.9921 17.1227C11.3759 16.7384 11.3759
 16.1138 10.9921 15.7301L4.2657 9.00373L10.9996 2.26989C11.1848
 2.08448 11.2871 1.83731 11.2871 1.57375C11.2871 1.3099 11.1848
 1.06273 10.9996 0.877167L10.4097 0.287563C10.2242 0.10215 9.97707
  3.70017e-06 9.71337 3.67712e-06C9.44966 3.65406e-06 9.20235 0.10215
  9.01708 0.287563L0.999388 8.30496C0.813682 8.49096 0.711683 8.7393
  0.712269 9.00329C0.711683 9.26832 0.813682 9.51651 0.999388 9.70236Z"
/>
</svg>
                </span>
                        </a>

                    {% else %}
                        <span class="arr-prew"><svg width="12" height="18" viewBox="0 0 12 18" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg">
<path d="M0.999388 9.70236L9.00962 17.7124C9.19488
17.8979 9.4422 18 9.7059 18C9.96961 18 10.2169 17.8979
 10.4022 17.7124L10.9921 17.1227C11.3759 16.7384 11.3759
 16.1138 10.9921 15.7301L4.2657 9.00373L10.9996 2.26989C11.1848
 2.08448 11.2871 1.83731 11.2871 1.57375C11.2871 1.3099 11.1848
 1.06273 10.9996 0.877167L10.4097 0.287563C10.2242 0.10215 9.97707
  3.70017e-06 9.71337 3.67712e-06C9.44966 3.65406e-06 9.20235 0.10215
  9.01708 0.287563L0.999388 8.30496C0.813682 8.49096 0.711683 8.7393
  0.712269 9.00329C0.711683 9.26832 0.813682 9.51651 0.999388 9.70236Z"
/>
</svg></span>
                    {% endif %}
                    {% for i in all_articles.paginator.page_range %}
                        {% if all_articles.number == i %}
                            <a class="num current"><span>{{ i }} <span class="sr-only"></span></span></a>
                        {% else %}
                            <a class="num" href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if all_articles.has_next %}
                        <a href="?page={{ all_articles.next_page_number }}">
                          <span class="arr-prew">
                            <svg width="12" height="18" viewBox="0 0 12 18"
                                 fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path d="M11.0006 8.29764L2.99038 0.287559C2.80512 0.102145
                                 2.5578 0 2.2941 0C2.03039 0 1.78308 0.102145 1.
                                  0.287559L1.00791 0.87731C0.624062 1.2616 0.624062 1.88618 1.00791
                                   2.26988L7.7343 8.99627L1.00045 15.7301C0.815182 15.9155 0.712891
                                   16.1627 0.712891 16.4263C0.712891 16.6901 0.815182 16.9373 1.00045
                                   17.1228L1.59035 17.7124C1.77576 17.8979 2.02293 18 2.28663 18C2.55034
                                   18 2.79765 17.8979 2.98292 17.7124L11.0006 9.69504C11.1863 9.50904
                                   11.2883 9.2607 11.2877 8.99671C11.2883 8.73168 11.1863 8.48349 11.0006 8.29764Z"
                                />
                            </svg>
                               </span>
                        </a>


                    {% else %}
                        <a class="disabled">
                            <span class="arr-next"> <svg width="12" height="18" viewBox="0 0 12 18"
                                                         fill="none"
                                                         xmlns="http://www.w3.org/2000/svg">
<path d="M11.0006 8.29764L2.99038 0.287559C2.80512 0.102145 2.5578 0
2.2941 0C2.03039 0 1.78308 0.102145 1.59781 0.287559L1.00791 0.87731C0.624062 1.2616 0.624062 1.88618 1.00791
2.26988L7.7343 8.99627L1.00045 15.7301C0.815182 15.9155 0.712891 16.1627 0.712891 16.4263C0.712891 16.6901
 0.815182 16.9373 1.00045 17.1228L1.59035 17.7124C1.77576 17.8979 2.02293 18 2.28663 18C2.55034 18 2.79765
  17.8979 2.98292 17.7124L11.0006 9.69504C11.1863 9.50904 11.2883 9.2607 11.2877 8.99671C11.2883 8.73168
   11.1863 8.48349 11.0006 8.29764Z"
/>
</svg>
                        </span>
                        </a>
                    {% endif %}
                {% endif %}
            </div>
        </section>
    </section>
    {% include 'includes/call_form_full.html' with section_class='price-form' wrap='price-block-form-wrap' form='price-block-form' %}

{% endblock %}

{% block js %}
    <script>
        App.home.init();
        App.category.init();
        // App.form.init();
    </script>
{% endblock %}

{% block extra_js %}
    <script>
        App.phone_mask('phone');
        App.scrool_to_block();
    </script>
{% endblock %}

intexdental/intexdental/templates/main/doctor.html
{% extends "index.html" %}
{% load i18n %}
{% load solo_tags %}
{% load poll_extras %}
{% load static %}

{% block title %} {{ doctor.fio }} {% endblock %}

{% block meta %}
    <meta name="author" content="Avalan.studio"/>
    <meta name="position" content="50.448091, 30.521688"/>
    <meta name="description"
          content="{{ doctor.meta_desc }}"/>

    <meta name="keywords"
          content="{{ doctor.meta_keywords }}"/>
    <meta name="copyright" content="{% trans 'Всі права належать' %} Avalan.studio"/>
{% endblock %}


{% block content %}
    <section class="doctors-over">
        {% include 'includes/breadcrumbs.html' %}
        <section class="service-content doctor-content">
            <div class="container">
                <div class="service-title">
                    <h1>{{ doctor.fio }}</h1>
                    <a href="#form" class="btn-contact">{% trans 'ЗАПИСАТЬСЯ НА ПРИЕМ' %}</a>
                </div>
            </div>
        </section>
        <section class="doctor-wrap">
            <div class="container">
                <div class="doctor-info-wrap">
                    <div class="doctor-info">
                        <p class="doctor-position">{{ doctor.occupation }}</p>
                        <div class="doctor-about">
                            {{ doctor.desc|safe }}
                        </div>
                        <p class="services-doctor-title">{% trans 'Услуги' %}</p>

                        <div class="services-doctor">
                            {% for service in doctor.services.all %}
                                <p style="display:block ;margin-bottom: 10px;
                                          text-decoration: none"
                                   class="service-doctor">{{ service.name }}</p>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="doctor-img">
                        <div class="doctor-img-wrap">
                            {% if doctor.photo %}
                                <img src="{{ doctor.photo.url }}" alt="">

                            {% endif %}
                        </div>
                    </div>
                </div>

            </div>
        </section>
    {% if doctor.get_certificates %}
        <section class="certificate-doctor">
            <div class="container">
                <p class="certificate-title">{% trans 'Сертификаты врача' %}</p>
                <div class="slider-certificate certificate-wrap-slider">
                    <div class="img-slider-certificate">
                        {% for cert in doctor.get_certificates %}
                            <div class="slide-certificate">
                                <img src="{{cert.img.url}}" alt="img-slide">
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    {% endif %}
        <section class="articles-doctor articles-slider doctors-wrap articles-wrap">
            <div class="container">
                <p class="certificate-title">{% trans 'Статьи врача' %}</p>
                <div class="slider-certificate">

                    <div class="{% if doctor.get_articles|length >= 3 %}slider-doctor-articles {% endif %} doctors-general">
                        {% for article in doctor.get_articles %}
                            <div class="slide-article doctor-one article-one">
                                <a href="{% url 'main:article' slug=article.slug %}" class="abs-link"></a>
                                <div class="slide-wrap">
                                    <div class="img-doctor-wrap">
                                        {% if article.photo %}
                                            <img src="{{ article.photo.url }}" alt="" class="doctor-img">
                                        {% else %}
                                            <img src="{% static 'images/doctor.png' %}" alt="" class="doctor-img">
                                        {% endif %}
                                        <div class="hover-article">
                                        </div>
                                    </div>
                                    <p class="doctor-name">{{ article.title }}</p>
                                    <p class="doctor-prof">{{ article.lead }}</p>
                                    <p class="article-date">{{ article.date }}</p>
                                </div>
                            </div>

                        {% endfor %}
                        {#                    Саша розберись с отображением если стaттей меньше 3#}
                    </div>
                </div>
            </div>
        </section>
    </section>
    {% include 'includes/call_form_full.html' %}
{% endblock %}

{% block js %}
    <script>
        App.home.init();
        App.slider.initDoctorPage();
        App.category.init();
        // App.form.init();
    </script>
{% endblock %}



{% block extra_js %}
    <script>
        App.phone_mask('phone');
        App.scrool_to_block();
    </script>
{% endblock %}

intexdental/intexdental/templates/main/doctors.html
{% extends "index.html" %}
{% load i18n %}
{% load solo_tags %}
{% load poll_extras %}
{% load static %}

{% block title %} {% trans 'Доктора' %} {% endblock %}

{% block meta %}
    {% get_solo 'meta.MetaCommand' as block_meta %}
    <meta name="author" content="Avalan.studio"/>
    <meta name="position" content="50.448091, 30.521688"/>
    <meta name="description"
          content="{{ block_meta.meta_desc }}"/>

    <meta name="keywords"
          content="{{ block_meta.meta_keywords }}"/>
    <meta name="copyright" content="{% trans 'Всі права належать' %} Avalan.studio"/>
{% endblock %}


{% block content %}
    {% get_doctors as doctors %}

    <section class="doctors-over">
        {% include 'includes/breadcrumbs.html' %}
        <section class="service-content">
            <div class="container">
                <div class="service-title">
                    <h1>{% trans 'Наша команда' %}</h1>
                    <a class="btn-contact js-anchor" data-to="form">{% trans 'ЗАПИСАТЬСЯ НА ПРИЕМ' %}</a>
                </div>
            </div>
        </section>
        <section class="doctors-wrap">
            <div class="container">
                <div class="doctors-general">
                    {% for doctor in doctors %}
                        <div class="doctor-one">
                            <div class="img-doctor-wrap">
                                {% if doctor.photo %}
                                    <img src="{{ doctor.photo.url }}" alt="" class="doctor-img">
                                {% else %}
                                    <img src="{% static 'images/doctor.png' %}" alt="" class="doctor-img">
                                {% endif %}
                                <div class="hover-doctor">
                                    <a href="{% url 'main:doctor' slug=doctor.slug %}"
                                       class="doctor-link">{% trans 'Подробнее о враче' %}</a>
                                    <a class="entry-link js-anchor" data-to="form">{% trans 'ЗАПИСАТЬСЯ НА ПРИЕМ' %}</a>
                                </div>
                            </div>
                            <p class="doctor-name">{{ doctor.fio }}</p>
                            <p class="doctor-prof">{{ doctor.occupation }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </section>
    {% include 'includes/call_form_full.html' %}
{% endblock %}

{% block js %}
    <script>
        App.home.init();
        App.category.init();
        // App.form.init();
    </script>
{% endblock %}


{% block extra_js %}
    <script>
        App.phone_mask('phone');
        App.scrool_to_block();
    </script>
{% endblock %}

intexdental/intexdental/templates/main/services.html
{% extends 'index.html' %}
{% load poll_extras %}
{% load i18n %}


{% block content %}
    {% get_category as categories %}
    {% include 'includes/breadcrumbs.html' %}
    <h1>{% trans 'цены' %}</h1>
    {% for category in categories %}
        <div class="category">
            <h3><a href="{% url 'main:category' slug=category.slug %}">{{ category.name }}</a></h3>
            <div class="sub-category-wrap">
                <ul style="margin-left: 50px">
                    {% for sub_cat in category.get_sub_category %}
                        <li>{{ sub_cat.name }} {{ sub_cat.price }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endfor %}


{% endblock %}